### ISSUE TITLE
Gradle Task to generate openapi.yml

### ISSUE THREAD

**Issue by ToberoCat** [tabilzad/ktor-docs-plugin#11]
Hi, first of all: Thank you for this amazing generator. It works perfectly for me. I  was wondering if there's a specific gradle task that's only generating the docs. I need it in my automated pipeline, where I first want to generate the newest openapi.yml file and then generate code from it for my frontend.

**Comment by tabilzad** [comment]
Hey I'm glad you found it useful. The plugin runs as part of the code compilation and therefore `compileKotlin` gradle task. So simply compiling your project with `./gradlew compileKotlin` would trigger openapi.yaml genmeration. You could also append  `--rerun-tasks` param in case you want to force gradle re-compile and ignore cache. Stay tuned for k2 support next week, it'll come with more features.

**Comment by ToberoCat** [comment]
Amazing, thank you
