### ISSUE TITLE
Create an example project 

### ISSUE THREAD

**Issue by piashcse** [tabilzad/ktor-docs-plugin#14]
Please create an example project I'm facing difficulties after running the project not getting swagger UI. I'm trying to shift the doc in this project 

Ref:
https://github.com/piashcse/ktor-E-Commerce

**Comment by tabilzad** [comment]
seems like this project is already using wrapping dsl from `com.papsign.ktor.openapigen`. This plugin will not be able to interpret ktor routes wrapped in third party frameworks. You have to use the native Ktor DSL.

**Comment by tabilzad** [comment]
you can reference the `use-module` as a setup example [here ](https://github.com/tabilzad/ktor-docs-plugin/tree/5534f1f9e41b4e0a7b6668a680cc02bad8bce2d5). I have removed it from this repository in the latest commit but will soon publish it to a separate repo.

**Comment by piashcse** [comment]
I will replace com.papsign.ktor.openapigen by your plugin. 

Adding this in routing level:

` routing {
                openAPI(path = "openapi", swaggerFile = "openapi/openapi.yaml")
                swaggerUI(path = "swagger", swaggerFile = "openapi/openapi.yaml")
            }
            routing {
                ordersRouting()
            }`
            
            But not getting anything in after hitting 
            http://localhost:8080/

**Comment by tabilzad** [comment]
assuming you have annotated you routing module with `@GenerateOpenApi`. Do you see the yaml file present under module's `build/resource/**`

**Comment by piashcse** [comment]
Yes it exist both for yaml and json in build/resources/**

**Comment by tabilzad** [comment]
I think it'd be served under `http://localhost:8080/openapi`

**Comment by piashcse** [comment]
Its showing something like this now under http://localhost:8080/openapi
![Uploading Screenshot 2024-08-14 at 11.34.40 PM.png…]()

**Comment by tabilzad** [comment]
Ok so it seems to be rendering the spec file correctly. You could also paste the yaml to `https://editor-next.swagger.io/` to see if it matches.

**Comment by piashcse** [comment]
Its working now but having different issue when try it. showing this error 

`These operation-level options override the global server options.`


<img width="1722" alt="Screenshot 2024-08-16 at 12 14 56 AM" src="https://github.com/user-attachments/assets/4af5cd97-83c7-4579-86c6-528d537107a3">
<img width="1726" alt="Screenshot 2024-08-16 at 12 15 12 AM" src="https://github.com/user-attachments/assets/7cf6f13e-3549-4681-ab14-51c726043708">

**Comment by tabilzad** [comment]
`These operation-level options override the global server options` is not an error. It's just telling you that picking a specific server from the dropdown would override the default swagger config which is always the same host exposing the docs. But if you wanted to configure other server(s) explicitly you'd have to add a root level `servers` block the `openapi.yaml` manually. I guess that would only be useful if you were to host the docs independently and have it target remote hosts. I could add a gradle config option to be able to specify remote servers at generation if that's useful. Lmk wyt

**Comment by piashcse** [comment]
I think it will be better if you give an option to determine the servers
