### ISSUE TITLE
Feature request: Handle templated and concatenated string in route paths

### ISSUE THREAD

**Issue by AlbRoehm** [tabilzad/ktor-docs-plugin#27]
As mentioned in the slack message it would be great to use const val strings, concatednated or templated strings for paths.

I tried to extend the `FirFunctionCall.extractArguments()` in ExpressionVisitorK2.kt which from my shallow understanding is doing this job but after a few hours i was not able to come up a pr. Somehow i was unable to extract the needed values out of the `FirStringConcatenationCall` and `FirPropertyAccessExpression`. I will try to follow your pr in case you can take this issue up to get some more understanding about the plugin world.

**Comment by tabilzad** [comment]
0.6.5 is released.
