### ISSUE TITLE
Add value class suppprt

### ISSUE THREAD

**Issue by 2ne1ugly** [tabilzad/ktor-docs-plugin#28]
Tested on 0.6.3-alpha

There are cases where we use value classes to give extra type safety and readability.
```kotlin
value class UserId(val value: String)
```

When serialized with kotlinx serializer, it is serialized as the internal field type and not as object(unless the internal type is an object).
Serializing the type above will give a json string.

But currently the generated openapi docs shows the wrapping object with a single field as if it was a regular data class.

**Comment by tabilzad** [comment]
Thanks for the feedback, I'll prioritize the value class support for 0.6.5
