### ISSUE TITLE
Adding operationId to openapi files

### ISSUE THREAD

**Issue by ToberoCat** [tabilzad/ktor-docs-plugin#33]
First of all, I really love this plugin, as it helped me on a lot of projects.
 
When generating code from `openapi.json`, I noticed that the `operationId` is missing. The `operationId` is crucial for generating more readable and meaningful names for the operations in the generated code. This would greatly improve the clarity and maintainability of the code, especially in larger projects.

**Proposed Enhancement**:  
Include a mechanism to ensure that the operationId is defined in the OpenAPI specification.
For example the Ktor responds annotation could support an `operation` label.

I've already thought about forking and adding it myself, but right now my schedule is a little bit limited.

Thank you for considering this feature!

**Comment by tabilzad** [comment]
hey glad you've found it helpful and thanks for a feature request. I think it'd make more sense to live in @KtorDescription annotation, @KtorResponds will likely go away once i figure out automatic response resolution :)

**Comment by tabilzad** [comment]
0.6.5 is released
