### ISSUE TITLE
Showing error in build.gradle.kts

### ISSUE THREAD

**Issue by piashcse** [tabilzad/ktor-docs-plugin#5]
Where will I add given code in build.gradle.kts? it shows an error. Please add documentation for build.gradle.kts

swagger {
    title = "Ktor Server"
    description = "Ktor Server Description"
    version = "1.0"
    requestFeature = true
}

**Comment by tabilzad** [comment]
@piashcse please take a look at the use-module for reference of placement the swagger config extension. If you keep getting an error please post the specific error details you are getting.
