### ISSUE TITLE
Absent tag when KtorDocs annotation is applied to Route

### ISSUE THREAD

**Issue by demen777** [tabilzad/ktor-docs-plugin#7]
If in https://github.com/tabilzad/ktor-docs-plugin/blob/7c3c3aa137aab645eb0956f68661283f0911ded0/create-plugin/src/test/resources/sources/Paths2.kt#L19C1-L19C41 change @KtorDocs to @KtorDocs(["tag2"]) then output json will not change

**Comment by demen777** [comment]
In README.md Planned features "Option for an automatic tag resolution from module/route function declaration"

**Comment by tabilzad** [comment]
Thanks for reporting the issue, it does seem to be a valid bug. The automatic tag resolution mentioned in the readme is for using the method names as tags, so they don't have to be declared in the annotations explicitly.

**Comment by tabilzad** [comment]
Fixed, will be included in 0.5.3-alpha release.
