### ISSUE TITLE
gradle task order compatibility issue

### ISSUE THREAD

**Issue by chris-brace** [tabilzad/ktor-docs-plugin#9]
I have a single `@KtorDocs` annotation on my app like this

```kotlin
@KtorDocs
fun Application.topLevelRoutes() {
    routing {
        base()
        articles()
    }
}
```

i serve the swagger UI as described in the ktor docs like this
```kotlin
        swaggerUI(path = "openapi", swaggerFile = "openapi.yaml") {
            version = "5.17.2"
        }
```

the first time i use `run` or `runshadow` the server fails to launch because the openapi file has yet to be generated

```
Exception in thread "main" java.io.FileNotFoundException: Swagger file not found: /home/ixtli/Public/project/kt/stavvy-sample-webserver/openapi.yaml
	at io.ktor.server.plugins.swagger.SwaggerKt.swaggerUI(Swagger.kt:44)
	at io.ktor.server.plugins.swagger.SwaggerKt.swaggerUI(Swagger.kt:36)
...
```
subsequent runs work fine, once the openapi yaml is present in the build dir

my gradle configuration relevant to this issue is

```kotlin
swagger {
    documentation {
        docsTitle = "Stavvy Example Ktor Server"
        docsDescription = "Server Description Here!"
        docsVersion = "1.0"
        generateRequestSchemas = true
        hideTransientFields = true
        hidePrivateAndInternalFields = true
    }

    pluginOptions {
        enabled = true
        saveInBuild = true
        format = "yaml"
    }
}

sourceSets {
    kotlin {
        main {
            resources {
                srcDir(layout.buildDirectory.dir("openapi"))
            }
        }
    }
}
```

it seems obvious to me that the task graph is wrong. perhaps the generation is a dependency of kotlin compilation where instead the AP should be run as an assembly dependency?

**Comment by tabilzad** [comment]
I think the resource processing task runs before kotlin compilation. But since the plugin is invoked during the compilation, you could redefine the gradle task with an explicit dependency on `compileKotlin` like this. 

```kotlin
tasks.named("processResources") {
    dependsOn("compileKotlin")
    doFirst {
        sourceSets["main"].resources.srcDir(layout.buildDirectory.dir("openapi"))
    }
}
```

**Comment by tabilzad** [comment]
Alternatively, if you adjust the plugin configuration to not `saveInBuild`, by default it will put the `openapi.yaml` under resources of the module. This way you wouldn't need to define additional gradle tasks to include the resources from build dir, but the documentation will be tracked in source control unless u gitignore it.  
```kotlin
routing {
        openAPI(path = "openapi", swaggerFile = "openapi/openapi.yaml"){

        }
    }
```

**Comment by chris-brace** [comment]
Thanks for the speedy reply! It's sorta shocking to me generation of the yaml file isn't a "first party" thing in ktor.

Making process resources dependent on compilekotlin seems dangerous because other gradle plugins which do stuff with the base or java plugins might not expect those deps to be reordered. I might have to resort to that, but what would really help me is to be able to address the generation task by name so that i could re-order just that. 

Also, unfortunately, changing `saveInBuild` doesn't change the situation because the yaml file is modified *after* its loaded by swaggerUI() / openAPI() functions. (You can test this by generating a starter ktor project and running the app. The first run will fail because the openapi.yaml file isn't present, then the second run will succeed.)

**Comment by tabilzad** [comment]
Unfortunately there isn't a gradle generation task to reference since all gradle does is passing the configuration arguments to the  compiler's command line processor, so file generation is invoked as part of the compiler's front-end code analysis phase, hence part of `:compileKotlin`. 

I'll get a patch up to have the `saveInBuild=true` option save to `build/resources/main/openapi/` instead of `build/openapi/`. That seems to do the trick without any additional gradle tasks. So lookout for 0.5.4 in the next few days.  

In terms of when `saveInbuild` is off,  I was able to recreate your issue with the file not being available at the first run. Will have to investigate some other ways to get it be included at the right time.

**Comment by chris-brace** [comment]
this fixed my issue!
